# Generated by Django 4.2.8 on 2023-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedselfie",
            name="selfie",
            field=models.ImageField(upload_to="selfies/"),
        ),
    ]
